In [71]:
DATASET ='/home/swei20/SymNormSlidingWindows/test/data/packets/equinix-nyc.dirA.20190117-131558.UTC.anon.pcap'

In [2]:
DATASET ='/home/swei20/SymNormSlidingWindows/data/testdata/test100.pcap'

In [29]:
from scapy.all import *
from ipaddress import IPv4Address as ipv4

In [4]:
import numpy as np
import math
import copy
import torch
LARGEPRIME = 2**61-1
# torch.random.manual_seed(42)

In [5]:
# p0=rdpcap(DATASET)

In [6]:
a = PcapReader(DATASET)

In [50]:
b='sport'

In [52]:
b[-4:]=='port'

True

In [8]:
aa

<IP  version=4 ihl=5 tos=0x0 len=1480 id=39507 flags=DF frag=0 ttl=56 proto=tcp chksum=0xf5ed src=89.86.97.24 dst=143.110.99.18 |<TCP  sport=https dport=49584 seq=1245547307 ack=3706341937 dataofs=5 reserved=0 flags=PA window=254 chksum=0xf070 urgptr=0 |>>

In [9]:
def store_port(x, out):
    out.append(x.dport)

In [45]:
def store_len(x, out=None):
    out.append(x.len)

In [32]:
query = lambda x: out.append(int(ipv4(x.src)))

In [48]:
name = ''

In [49]:
'rand' + name

'rand'

In [151]:
def get_traffic_stream(NAME, DATASET, m = None, save=True):
    out=[]
    if NAME == 'src':
        def store_src(x, out=out):
            try: 
                out.append(int(ipv4(x.src)))
            except:
                pass
        query = lambda x: store_src(x)
    elif NAME == 'dst':
        query = lambda x: out.append(int(ipv4(x.dst)))
    elif NAME =='sport':
        query = lambda x: out.append(x.sport)
    elif NAME =='dport':
        query = lambda x: out.append(x.dport)
    elif NAME =='len':
        query = lambda x: out.append(x.len)      
    sniff(offline=DATASET, prn=query,count= m, store = 0)
    print(m, out)
    if save:
        if (m <= 1000) and (m >=10 ):
            np.savetxt(f'/home/swei20/SymNormSlidingWindows/test/data/stream/traffic_{NAME}_m{m}.txt', out)
        elif (m >1000) or (m ==-1):
            np.savetxt(f'/home/swei20/SymNormSlidingWindows/data/stream/traffic_{NAME}.txt', out)
    return out

In [ ]:
sniff(filter = ,offline=DATASET, prn=query,count= m, store = 0)

In [153]:
outfull = get_traffic_stream('src', DATASET, m=-1 ,save =1)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [149]:
out2=get_traffic_stream('src', DATASET, m=10)

AddressValueError: Expected 4 octets in '2158:2601:ffed:11c::'

In [146]:
out22=np.loadtxt('/home/swei20/SymNormSlidingWindows/test/data/stream/traffic_src_m100.txt')

In [91]:
# out2

In [94]:
from collections import Counter

In [147]:
c = Counter(out22)

In [148]:
c.values()

dict_values([1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 4, 3, 1, 1, 8, 1, 1, 1, 1, 3, 1, 2, 1, 1, 1, 7, 4, 2, 1, 1, 1, 1, 2, 4, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1])

In [80]:
out=get_traffic_stream('sport',DATASET, m=-1)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [81]:
len(out)

769157

In [73]:
NAME = 'sport'
m=100

In [78]:
len(aaa[:100])

100

In [123]:
a = np.array(7.6811457, dtype='float32')

In [139]:
np.log2(500000/0.05)

23.253496664211536

In [141]:
stream = out

In [142]:
stream

[443,
 443,
 80,
 443,
 443,
 80,
 4554,
 443,
 443,
 443,
 443,
 2515,
 443,
 443,
 5536,
 25461,
 25461,
 25461,
 25461,
 25461,
 2515,
 45722,
 45722,
 45722,
 80,
 443,
 80,
 25461,
 443,
 80,
 80,
 80,
 41363,
 80,
 443,
 80,
 80,
 80,
 57676,
 80,
 443,
 3020,
 80,
 443,
 443,
 80,
 443,
 443,
 57676,
 443,
 80,
 443,
 443,
 2515,
 443,
 25271,
 80,
 80,
 25461,
 80,
 443,
 80,
 80,
 443,
 443,
 80,
 443,
 38026,
 54613,
 80,
 51567,
 993,
 25461,
 8195,
 36764,
 443,
 51567,
 25461,
 443,
 80,
 993,
 25461,
 80,
 38026,
 80,
 80,
 443,
 57676,
 80,
 80,
 25461,
 25271,
 80,
 25461,
 80,
 80,
 80,
 80,
 25461,
 80,
 80,
 443,
 80,
 143,
 80,
 443,
 80,
 443,
 443,
 80,
 25461,
 54675,
 80,
 443,
 443,
 443,
 443,
 443,
 443,
 443,
 443,
 80,
 80,
 8883,
 491,
 25461,
 80,
 80,
 7172,
 25461,
 443,
 25461,
 993,
 5223,
 25461,
 443,
 80,
 52631,
 25461,
 25461,
 65064,
 25461,
 443,
 25461,
 25461,
 48497,
 25461,
 48497,
 80,
 80,
 25461,
 25461,
 31985,
 25,
 25461,
 25461,
 443

In [ ]:
Counter()

In [128]:
Counter(keys = list(range(100)))

Counter({'keys': [0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          23,
          24,
          25,
          26,
          27,
          28,
          29,
          30,
          31,
          32,
          33,
          34,
          35,
          36,
          37,
          38,
          39,
          40,
          41,
          42,
          43,
          44,
          45,
          46,
          47,
          48,
          49,
          50,
          51,
          52,
          53,
          54,
          55,
          56,
          57,
          58,
          59,
          60,
          61,
          62,
          63,
          64,
          65,
          66,
          67,
          68,
          69,
          70,
        

In [125]:
float(a)

7.681145668029785

In [127]:
np.log10(10000/0.01)

6.0

In [122]:
a.__d

AttributeError: 'numpy.ndarray' object has no attribute '__dict__'

In [77]:
len(aaa)

100

In [74]:
aaa = np.loadtxt(f'/home/swei20/SymNormSlidingWindows/test/data/stream/traffic_{NAME}_m{m}.txt')

In [76]:
aaa[78]

443.0

In [ ]:
get_traffic_stream('src',m=-1)

In [47]:
get_traffic_stream('src',m=-1)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [17]:
outsPort=[]
sniff(filter="tcp",
      offline=DATASET,
      prn=lambda x: outsPort.append(int(ipv4(x.src)),count= 3, store = 0)

<Sniffed: TCP:0 UDP:0 ICMP:0 Other:0>

In [18]:
np.savetxt('traffic_sport.txt',outsPort)

In [16]:
np.savetxt('traffic_dport.txt',outPort)

In [19]:
import netaddr

In [22]:
ip = netaddr.IPAddress('89.86.97.24')
ip.value

1498833176

In [23]:
w,x,y,z = 89,86,97,24

In [28]:
int(ip('89.86.97.24'))

1498833176

In [ ]:
int(ipaddress.IPv4Address('192.168.0.1'))
3232235521

In [24]:
 16777216*w + 65536*x + 256*y + z 

1498833176

In [20]:
89**4 + 86**3 + 97**2 +24

63387730

In [61]:
out=[]
sniff(filter="ip",
      offline=DATASET,
      prn=lambda x: out.append(x.src),count= -1, store = 0)


<Sniffed: TCP:0 UDP:0 ICMP:0 Other:0>

In [62]:
out

[1480,
 64,
 1500,
 424,
 219,
 101,
 40,
 1400,
 103,
 200,
 138,
 1480,
 1452,
 1452,
 1452,
 52,
 1452,
 321,
 40,
 1480,
 1480,
 1480,
 133,
 1480,
 1480,
 380,
 52,
 119,
 119,
 52,
 52,
 52,
 514,
 1500,
 52,
 1500,
 1480,
 64,
 45,
 399,
 1500,
 1500,
 1500,
 40,
 93,
 1500,
 40,
 103,
 1500,
 1500,
 1500,
 52,
 1500,
 1455,
 52,
 52,
 1500,
 160,
 1500,
 759,
 1500,
 1480,
 1452,
 83,
 60,
 1480,
 1500,
 1452,
 60,
 52,
 56,
 479,
 40,
 100,
 1500,
 1500,
 1480,
 65,
 1500,
 52,
 1500,
 1400,
 1462,
 1462,
 1500,
 1480,
 1199,
 40,
 40,
 1199,
 1500,
 40,
 1500,
 1480,
 176,
 86,
 178,
 1500,
 40,
 1400,
 1500,
 1500,
 710,
 384,
 136,
 1400,
 1500,
 40,
 1500,
 1480,
 52,
 52,
 213,
 1500,
 91,
 1480,
 1400,
 229,
 83,
 339,
 1480,
 1400,
 1500,
 1500,
 63,
 1500,
 52,
 393,
 1500,
 1480,
 1500,
 1455,
 1480,
 1480,
 1480,
 46,
 52,
 1400,
 1500,
 1400,
 52,
 1500,
 78,
 1480,
 40,
 1156,
 1500,
 40,
 681,
 48,
 1480,
 52,
 1448,
 1480,
 1448,
 1448,
 400,
 1480,
 1480,
 754,


In [66]:
max(out)

1500

In [65]:
len(out)

974329

In [64]:
np.savetxt('../data/stream/traffic.txt', out)

In [36]:
out=[]
stream = list(sniff(filter="ip",
      offline=DATASET,
      prn=lambda x: x.len,count= -1, store = 0))

1480
64
1500


In [37]:
stream

[]

In [18]:
a = sniff(offline=DATASET,prn=len,store=0, count = 10)

40
64
52
28
28
52
40
52
52
28


In [20]:
for packet in p0[:2]:
    # We're only interested packets with a DNS Round Robin layer

    print(packet)
    if packet.haslayer(DNSRR):
        # If the an(swer) is a DNSRR, print the name it replied with.
        if isinstance(packet.an, DNSRR):
#             print(packet.an.rrname)
            pass

b'E\x00\x05\xc8\x9aS@\x008\x06\xf5\xedYVa\x18\x8fnc\x12\x01\xbb\xc1\xb0J=\x8b+\xdc\xeaJ1P\x18\x00\xfe\xf0p\x00\x00'
b'E\x08\x00@\x0f\xa9@\x00\xed\x06kH4p#^\xab\xc6\x0f*\x01\xbb\x92\xda\x9a\xa1^\xb2\xbf\x84\x8b\xd4\xb0\x10\x00u\n\xa9\x00\x00\x01\x01\x08\n\nT`O\x00\xcaG\xe5\x01\x01\x05\n\xbf\x84\x8bV\xbf\x84\x8b\xd4'


In [29]:
p00 = p0[:100]

In [32]:
wrpcap('test100.pcap', p00)

In [24]:
pckIter = iter(p0)

In [25]:
pck = next(pckIter)

In [26]:
item = pck.len

1480

In [42]:
ip = netaddr.IPAddress('89.86.97.24')

In [43]:
ip.value

1498833176

In [23]:

packet.len

64

In [13]:
packet

<IP  version=4 ihl=5 tos=0x0 len=1480 id=39507 flags=DF frag=0 ttl=56 proto=tcp chksum=0xf5ed src=89.86.97.24 dst=143.110.99.18 |<TCP  sport=https dport=49584 seq=1245547307 ack=3706341937 dataofs=5 reserved=0 flags=PA window=254 chksum=0xf070 urgptr=0 |>>

In [14]:
packet.src

'89.86.97.24'

In [6]:
for p0

<equinix-nyc.dirA.20190117-131558.UTC.anon.pcap: TCP:769157 UDP:202097 ICMP:7253 Other:9189>

PermissionError: [Errno 1] Operation not permitted

In [3]:
np.random.seed(42)
stream = np.random.randint(1,n,size=n)
exactL2 = np.linalg.norm(stream, ord=2)

In [4]:
np.sort(stream)[::-1]

array([95, 93, 93, 92, 92, 91, 90, 90, 89, 89, 89, 88, 88, 87, 87, 85, 84,
       83, 82, 81, 80, 80, 78, 78, 76, 75, 75, 74, 73, 72, 72, 71, 64, 64,
       63, 62, 62, 62, 62, 62, 61, 60, 60, 60, 60, 59, 58, 55, 54, 54, 53,
       53, 53, 52, 51, 51, 50, 49, 48, 47, 47, 44, 44, 42, 40, 39, 38, 36,
       35, 34, 33, 30, 26, 24, 24, 22, 22, 21, 21, 21, 18, 18, 15, 15, 15,
       14, 14,  9,  8,  7,  6,  4,  4,  4,  3,  3,  2,  2,  2,  2])

In [5]:
stream, exactL2

(array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75, 88, 24,  3, 22, 53,  2, 88,
        30, 38,  2, 64, 60, 21, 33, 76, 58, 22, 89, 49, 91, 59, 42, 92, 60,
        80, 15, 62, 62, 47, 62, 51, 55, 64,  3, 51,  7, 21, 73, 39, 18,  4,
        89, 60, 14,  9, 90, 53,  2, 84, 92, 60, 71, 44,  8, 47, 35, 78, 81,
        36, 50,  4,  2,  6, 54,  4, 54, 93, 63, 18, 90, 44, 34, 74, 62, 14,
        95, 48, 15, 72, 78, 87, 62, 40, 85, 80, 82, 53, 24, 26, 89]),
 583.0583161228386)

In [124]:
c=2
r=100
d, k=None, None
device='cuda'
streamTr=torch.tensor(stream, dtype=torch.int64)
item=streamTr[2]
streamTr0=streamTr[:10]

In [123]:
run(streamTr, c, r, device)

tensor([7.0583], device='cuda:0')
tensor([10.3368,  7.0679], device='cuda:0')
tensor([12.3282,  7.0583], device='cuda:0')
tensor([13.9998,  7.0679], device='cuda:0')
tensor([15.2962,  9.9995,  7.0707], device='cuda:0')
tensor([16.5551, 10.0990,  7.0707], device='cuda:0')
tensor([17.9938,  9.8990,  7.0707], device='cuda:0')
tensor([18.6862,  9.5894,  7.0707], device='cuda:0')
tensor([19.4651,  9.8949,  7.0679], device='cuda:0')
tensor([22.5514, 14.1358,  7.0679], device='cuda:0')
tensor([23.4135, 15.4092,  9.6816,  7.0679], device='cuda:0')
tensor([24.8781, 12.7124, 10.2395,  7.0654], device='cuda:0')
tensor([25.4337, 14.6603, 12.5698,  7.0536], device='cuda:0')
tensor([26.5432, 13.6746,  9.3754,  7.0679], device='cuda:0')
tensor([28.2356, 16.2268, 12.1611,  7.0353], device='cuda:0')
tensor([28.2168, 17.9357, 14.0340,  7.0622], device='cuda:0')
tensor([31.0121, 16.3697, 10.2791,  7.0679], device='cuda:0')
tensor([31.5767, 17.4596, 12.2045,  7.0622], device='cuda:0')
tensor([31.7520, 18.

tensor([100.6223,  54.5115,  38.9238,  21.2124,  13.9641,   7.0707],
       device='cuda:0')